name: Test Project

jobs:
  - name: Clone
    url: git@github.com:randuck-dev/diy-ci.git

  - name: Build
    run: |
      echo "Hello World"
      sleep 1
  - name: Test
    run: |
      echo "Testing"
      sleep 0.5

  - name: Upload Artifacts
    run: |
      echo "Uploading Artifacts to registry"
      curl ifconfig.net
